INSERT INTO USERS (ID, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (1, 'user@example.com', 'Naurlox', 'naurlox', '1234567');

-- password: 123456
INSERT INTO ACCOUNT (ID, ACCOUNTEXPIRED, ACCOUNTLOCKED, CREATEDON, CREDENTIALSEXPIRED, ENABLED, PASSWORD, USERNAME, USER_ID) VALUES (1, FALSE, FALSE, '2023-04-27', FALSE, TRUE, '$2a$10$cYLM.qoXpeAzcZhJ3oXRLu9Slkb61LHyWW5qJ4QKvHEMhaxZ5qCPi', 'user', 1);

INSERT INTO CUSTOMER (USER_ID) VALUES (1);

INSERT INTO ROLE (ACCOUNT_ID, ROLE) VALUES (1, 'REGISTERED_CUSTOMER');


INSERT INTO USERS (ID, EMAIL, FIRSTNAME, LASTNAME, PHONENUMBER) VALUES (2, 'admin@example.com', 'admin', 'lox', '1234567');

-- password: 123456
INSERT INTO ACCOUNT (ID, ACCOUNTEXPIRED, ACCOUNTLOCKED, CREATEDON, CREDENTIALSEXPIRED, ENABLED, PASSWORD, USERNAME, USER_ID) VALUES (2, FALSE, FALSE, '2023-04-27', FALSE, TRUE, '$2a$10$cYLM.qoXpeAzcZhJ3oXRLu9Slkb61LHyWW5qJ4QKvHEMhaxZ5qCPi', 'admin', 2);

INSERT INTO ROLE (ACCOUNT_ID, ROLE) VALUES (2,       'ADMIN');